#################
### AUTOSTART ###
#################
exec-once = ~/.config/waybar/scripts/launch.sh
exec-once = awww-daemon
exec-once = snappy-switch --daemon & disown
exec-once = wl-paste -t text --watch clipman store --no-persist
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
exec-once = wl-clip-persist --clipboard regular
exec-once = hypridle
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = squeekboard
exec-once = systemctl --user enable --now vicinae
