include ~/.cache/wal/colors-kitty.conf

background_opacity 1
font_family Maple Mono
font_size 18
# The thickness of the trail (0.0 to 1.0)
cursor_trail 1

# How long the trail lasts in seconds
cursor_trail_decay 0.1 0.4

# The distance (in cells) the cursor must move to trigger the trail
cursor_trail_start_threshold 2

# Set to 0 to disable blinking, or a negative value to follow system settings
cursor_blink_interval 0.5

# Stop blinking after this many seconds of inactivity
cursor_stop_blinking_after 15.0

# Force the trail to use pywal cursor color
# 'cursor' is a variable defined inside ~/.cache/wal/colors-kitty.conf
cursor_trail_color none

# Enable remote control
allow_remote_control yes

# Choose how kitty listens for connections
# 'unix:/tmp/mykitty' is a common choice for a control socket
listen_on unix:/tmp/mykitty

window_padding_width 8
