$image = Null

$background = rgba(151313ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(323030ff)

$inverse_primary = rgba(6d595cff)

$inverse_surface = rgba(e7e1e1ff)

$on_background = rgba(e7e1e1ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(3d2c2fff)

$on_primary_container = rgba(ffffffff)

$on_primary_fixed = rgba(26181aff)

$on_primary_fixed_variant = rgba(544245ff)

$on_secondary = rgba(372e2fff)

$on_secondary_container = rgba(ebdddeff)

$on_secondary_fixed = rgba(211a1bff)

$on_secondary_fixed_variant = rgba(4e4446ff)

$on_surface = rgba(e7e1e1ff)

$on_surface_variant = rgba(d1c3c4ff)

$on_tertiary = rgba(3b2e21ff)

$on_tertiary_container = rgba(ffffffff)

$on_tertiary_fixed = rgba(25190eff)

$on_tertiary_fixed_variant = rgba(534436ff)

$outline = rgba(9a8e8fff)

$outline_variant = rgba(4e4446ff)

$primary = rgba(dac0c4ff)

$primary_container = rgba(6f5b5eff)

$primary_fixed = rgba(f7dcdfff)

$primary_fixed_dim = rgba(dac0c4ff)

$scrim = rgba(000000ff)

$secondary = rgba(d1c3c4ff)

$secondary_container = rgba(4e4446ff)

$secondary_fixed = rgba(eedfe0ff)

$secondary_fixed_dim = rgba(d1c3c4ff)

$shadow = rgba(000000ff)

$source_color = rgba(6f5b5eff)

$surface = rgba(151313ff)

$surface_bright = rgba(3b3839ff)

$surface_container = rgba(211f1fff)

$surface_container_high = rgba(2c2929ff)

$surface_container_highest = rgba(373434ff)

$surface_container_low = rgba(1d1b1bff)

$surface_container_lowest = rgba(100e0eff)

$surface_dim = rgba(151313ff)

$surface_tint = rgba(dac0c4ff)

$surface_variant = rgba(4e4446ff)

$tertiary = rgba(d8c3b0ff)

$tertiary_container = rgba(6d5d4eff)

$tertiary_fixed = rgba(f5dfccff)

$tertiary_fixed_dim = rgba(d8c3b0ff)

