$image = Null

$background = rgba(131314ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(313031ff)

$inverse_primary = rgba(585e6eff)

$inverse_surface = rgba(e5e2e3ff)

$on_background = rgba(e5e2e3ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(2a303fff)

$on_primary_container = rgba(fefcffff)

$on_primary_fixed = rgba(151b29ff)

$on_primary_fixed_variant = rgba(414756ff)

$on_secondary = rgba(2e3037ff)

$on_secondary_container = rgba(e3e3ecff)

$on_secondary_fixed = rgba(191b21ff)

$on_secondary_fixed_variant = rgba(45474dff)

$on_surface = rgba(e5e2e3ff)

$on_surface_variant = rgba(c6c6ccff)

$on_tertiary = rgba(3c2b37ff)

$on_tertiary_container = rgba(fffcffff)

$on_tertiary_fixed = rgba(261722ff)

$on_tertiary_fixed_variant = rgba(53414eff)

$outline = rgba(909096ff)

$outline_variant = rgba(45464cff)

$primary = rgba(c0c6d9ff)

$primary_container = rgba(515767ff)

$primary_fixed = rgba(dde2f5ff)

$primary_fixed_dim = rgba(c0c6d9ff)

$scrim = rgba(000000ff)

$secondary = rgba(c5c6ceff)

$secondary_container = rgba(474950ff)

$secondary_fixed = rgba(e1e2eaff)

$secondary_fixed_dim = rgba(c5c6ceff)

$shadow = rgba(000000ff)

$source_color = rgba(515767ff)

$surface = rgba(131314ff)

$surface_bright = rgba(39393aff)

$surface_container = rgba(201f21ff)

$surface_container_high = rgba(2a2a2bff)

$surface_container_highest = rgba(353436ff)

$surface_container_low = rgba(1b1b1dff)

$surface_container_lowest = rgba(0e0e0fff)

$surface_dim = rgba(131314ff)

$surface_tint = rgba(c0c6d9ff)

$surface_variant = rgba(45464cff)

$tertiary = rgba(d8c0cfff)

$tertiary_container = rgba(65525fff)

$tertiary_fixed = rgba(f5dbebff)

$tertiary_fixed_dim = rgba(d8c0cfff)

