$image = Null

$background = rgba(111412ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(2e312eff)

$inverse_primary = rgba(3b674cff)

$inverse_surface = rgba(e2e3dfff)

$on_background = rgba(e2e3dfff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(083820ff)

$on_primary_container = rgba(000000ff)

$on_primary_fixed = rgba(002110ff)

$on_primary_fixed_variant = rgba(234f35ff)

$on_secondary = rgba(233429ff)

$on_secondary_container = rgba(d1e5d4ff)

$on_secondary_fixed = rgba(0f1f15ff)

$on_secondary_fixed_variant = rgba(3a4b3eff)

$on_surface = rgba(e2e3dfff)

$on_surface_variant = rgba(c1c9c0ff)

$on_tertiary = rgba(1a3053ff)

$on_tertiary_container = rgba(000000ff)

$on_tertiary_fixed = rgba(011b3dff)

$on_tertiary_fixed_variant = rgba(32476bff)

$outline = rgba(8b938bff)

$outline_variant = rgba(414942ff)

$primary = rgba(a2d2b0ff)

$primary_container = rgba(6d9b7cff)

$primary_fixed = rgba(bdeecbff)

$primary_fixed_dim = rgba(a2d2b0ff)

$scrim = rgba(000000ff)

$secondary = rgba(b8cbbbff)

$secondary_container = rgba(3a4b3eff)

$secondary_fixed = rgba(d4e8d7ff)

$secondary_fixed_dim = rgba(b8cbbbff)

$shadow = rgba(000000ff)

$source_color = rgba(6c9a7bff)

$surface = rgba(111412ff)

$surface_bright = rgba(373a37ff)

$surface_container = rgba(1e201eff)

$surface_container_high = rgba(282b28ff)

$surface_container_highest = rgba(333533ff)

$surface_container_low = rgba(1a1c1aff)

$surface_container_lowest = rgba(0c0f0dff)

$surface_dim = rgba(111412ff)

$surface_tint = rgba(a2d2b0ff)

$surface_variant = rgba(414942ff)

$tertiary = rgba(b2c7f2ff)

$tertiary_container = rgba(7c91b9ff)

$tertiary_fixed = rgba(d6e3ffff)

$tertiary_fixed_dim = rgba(b2c7f2ff)

