# _    _                  _                 _ 
#| |  | |                | |               | |
#| |__| |_   _ _ __  _ __| | __ _ _ __   __| |
#|  __  | | | | '_ \| '__| |/ _` | '_ \ / _` |
#| |  | | |_| | |_) | |  | | (_| | | | | (_| |
#|_|  |_|\__, | .__/|_|  |_|\__,_|_| |_|\__,_|
#         __/ | |                             
#        |___/|_|                             

source = /home/bixer/.config/hypr/hyprland-gui.conf
source = colors.conf
source = ~/.cache/wal/colors-hyprland.conf
source = ~/.config/hypr/components/monitors.conf
source = ~/.config/hypr/components/default_apps.conf
source = ~/.config/hypr/components/autostart.conf
source = ~/.config/hypr/components/environment_variables.conf
source = ~/.config/hypr/components/permissions.conf
source = ~/.config/hypr/components/animations.conf
source = ~/.config/hypr/components/look_and_feel.conf
source = ~/.config/hypr/components/input.conf
source = ~/.config/hypr/components/binds.conf
source = ~/.config/hypr/components/windows_and_workspaces.conf
