--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/bixer/wallpapers/naruto.png"

-- Special
background="#181915"
foreground="#ddd1bc"
cursor="#ddd1bc"

-- Colors
color0="#181915"
color1="#50B448"
color2="#668B75"
color3="#A99068"
color4="#E8AE53"
color5="#D5A96D"
color6="#669787"
color7="#ddd1bc"
color8="#9a9283"
color9="#50B448"
color10="#668B75"
color11="#A99068"
color12="#E8AE53"
color13="#D5A96D"
color14="#669787"
color15="#ddd1bc"
