$wallpaper = /home/bixer/wallpapers/Mountain.png	
$foreground = rgb(c1caca)
$background = rgb(0d0d0d)
$color0 = rgb(0d0d0d)
$color1 = rgb(687576)
$color2 = rgb(75817E)
$color3 = rgb(6B7E81)
$color4 = rgb(77898B)
$color5 = rgb(869896)
$color6 = rgb(90A19F)
$color7 = rgb(c1caca)
$color8 = rgb(878d8d)
$color9 = rgb(687576)
$color10 = rgb(75817E)
$color11 = rgb(6B7E81)
$color12 = rgb(77898B)
$color13 = rgb(869896)
$color14 = rgb(90A19F)
$color15 = rgb(c1caca)
