foreground   #e8e2dc
background   #0f0f18
cursor       #e8e2dc

color0       #0f0f18
color8       #a29e9a
color1       #7E8197
color9       #7E8197
color2       #9D9AAA
color10      #9D9AAA
color3       #C2B8BD
color11      #C2B8BD
color4       #D3D1BB
color12      #D3D1BB
color5       #C2BBC2
color13      #C2BBC2
color6       #D4D3CC
color14      #D4D3CC
color7       #e8e2dc
color15      #e8e2dc
