$wallpaper = /home/bixer/wallpapers/Castle.png	
$foreground = rgb(e8e2dc)
$background = rgb(0f0f18)
$color0 = rgb(0f0f18)
$color1 = rgb(7E8197)
$color2 = rgb(9D9AAA)
$color3 = rgb(C2B8BD)
$color4 = rgb(D3D1BB)
$color5 = rgb(C2BBC2)
$color6 = rgb(D4D3CC)
$color7 = rgb(e8e2dc)
$color8 = rgb(a29e9a)
$color9 = rgb(7E8197)
$color10 = rgb(9D9AAA)
$color11 = rgb(C2B8BD)
$color12 = rgb(D3D1BB)
$color13 = rgb(C2BBC2)
$color14 = rgb(D4D3CC)
$color15 = rgb(e8e2dc)
