# Shell variables
# Generated by 'wal'
wallpaper='/home/bixer/wallpapers/Mountain.png'

# Special
background='#0d0d0d'
foreground='#c1caca'
cursor='#c1caca'

# Colors
color0='#0d0d0d'
color1='#687576'
color2='#75817E'
color3='#6B7E81'
color4='#77898B'
color5='#869896'
color6='#90A19F'
color7='#c1caca'
color8='#878d8d'
color9='#687576'
color10='#75817E'
color11='#6B7E81'
color12='#77898B'
color13='#869896'
color14='#90A19F'
color15='#c1caca'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
