--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/bixer/wallpapers/Mountain.png"

-- Special
background="#0d0d0d"
foreground="#c1caca"
cursor="#c1caca"

-- Colors
color0="#0d0d0d"
color1="#687576"
color2="#75817E"
color3="#6B7E81"
color4="#77898B"
color5="#869896"
color6="#90A19F"
color7="#c1caca"
color8="#878d8d"
color9="#687576"
color10="#75817E"
color11="#6B7E81"
color12="#77898B"
color13="#869896"
color14="#90A19F"
color15="#c1caca"
