--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/bixer/wallpapers/Castle.png"

-- Special
background="#0f0f18"
foreground="#e8e2dc"
cursor="#e8e2dc"

-- Colors
color0="#0f0f18"
color1="#7E8197"
color2="#9D9AAA"
color3="#C2B8BD"
color4="#D3D1BB"
color5="#C2BBC2"
color6="#D4D3CC"
color7="#e8e2dc"
color8="#a29e9a"
color9="#7E8197"
color10="#9D9AAA"
color11="#C2B8BD"
color12="#D3D1BB"
color13="#C2BBC2"
color14="#D4D3CC"
color15="#e8e2dc"
