# Shell variables
# Generated by 'wal'
wallpaper='/home/bixer/wallpapers/Space Nord.png'

# Special
background='#242129'
foreground='#c9c8ba'
cursor='#c9c8ba'

# Colors
color0='#242129'
color1='#956566'
color2='#C4656C'
color3='#938C79'
color4='#B39379'
color5='#CD9B7A'
color6='#797E84'
color7='#c9c8ba'
color8='#8c8c82'
color9='#956566'
color10='#C4656C'
color11='#938C79'
color12='#B39379'
color13='#CD9B7A'
color14='#797E84'
color15='#c9c8ba'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
