$wallpaper = /home/bixer/wallpapers/naruto.png	
$foreground = rgb(ddd1bc)
$background = rgb(181915)
$color0 = rgb(181915)
$color1 = rgb(50B448)
$color2 = rgb(668B75)
$color3 = rgb(A99068)
$color4 = rgb(E8AE53)
$color5 = rgb(D5A96D)
$color6 = rgb(669787)
$color7 = rgb(ddd1bc)
$color8 = rgb(9a9283)
$color9 = rgb(50B448)
$color10 = rgb(668B75)
$color11 = rgb(A99068)
$color12 = rgb(E8AE53)
$color13 = rgb(D5A96D)
$color14 = rgb(669787)
$color15 = rgb(ddd1bc)
