# Shell variables
# Generated by 'wal'
wallpaper='/home/bixer/wallpapers/naruto.png'

# Special
background='#181915'
foreground='#ddd1bc'
cursor='#ddd1bc'

# Colors
color0='#181915'
color1='#50B448'
color2='#668B75'
color3='#A99068'
color4='#E8AE53'
color5='#D5A96D'
color6='#669787'
color7='#ddd1bc'
color8='#9a9283'
color9='#50B448'
color10='#668B75'
color11='#A99068'
color12='#E8AE53'
color13='#D5A96D'
color14='#669787'
color15='#ddd1bc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
